### ISSUE TITLE
Timeline Cutsout Silent Sections of the Video

### ISSUE THREAD

**Issue by koyukan** [erwinv/yaffu#3]
Hello Erwin, 

Thanks for the great effort, this is an amazing tool, It's very useful to stitch Janus conferences. However there is a case where your tool gets rid of videos where no audio is present and it renders black screen instead. This was not very useful for me as there are cases where the participant may choose to disable mic and only turn the cam on.  So, I made a small pull request, I added changes to keep the silent sections in the final video. I made it optional so it's not a breaking change, if people want to use it the way you intended it, they still can. Also, if you want me to add/change some things regarding this, please let me know.

**Comment by erwinv** [comment]
Hello, thanks for the kind words. I haven't used this tool for a long time and I am pleasantly surprised that it is actually used.

If I remember correctly, we forked Janus and modified it to produce silent audio when a participant mutes their mic (so the audio files are continuous and not cut/split every time the mic is muted and unmuted). So my implementation may have inherited that incorrect assumption.

I have accepted and merged your PR, thanks!

**Comment by koyukan** [comment]
I am also surprised, by the fact that your tool is not being used by many people who use Janus. As I can see many of them are struggling with processing conference recordings, it's not an easy task and your code helps :)  And I understand the reason behind your design decisions. Thanks again for your effort.
